leciona(aeda, aldaberto).
leciona(bdad, bernardete).
leciona(comp, capitolino).
leciona(mest, diogenes).
leciona(rc, ermelinda).
frequenta(aeda, alberto).
frequenta(aeda, bruna).
frequenta(aeda, cristina).
frequenta(aeda, diogo).
frequenta(aeda, eduarda).
frequenta(bdad, antonio).
frequenta(bdad, bruno).
frequenta(bdad, cristina).
frequenta(bdad, duarte).
frequenta(bdad, eduardo).
frequenta(comp, alberto).
frequenta(comp, bernardo).
frequenta(comp, clara).
frequenta(comp, diana).
frequenta(comp, eurico).
frequenta(mest, antonio).
frequenta(mest, bruna).
frequenta(mest, claudio).
frequenta(mest, duarte).
frequenta(mest, eva).
frequenta(rc, alvaro).
frequenta(rc, beatriz).
frequenta(rc, claudio).
frequenta(rc, diana).
frequenta(rc, eduardo).
